### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by Sepehr2016** [ajbowler/clarifai-photo-sorter#1]
So I'm a newbie and don't have any experiences with Python just than simple beginner codes. I thought maybe I should wait and master Python, but this tool is so interesting that I can't wait any longer to see it sorting my photo collection! 

Things that I've done so far:
**1.** Installed Python 2.7 on my computer (OS: Windows 7 64-bit)
**2.** Signed up on Clarifai's website
**3.** Headed to [Clarifai API Python Client](https://github.com/Clarifai/clarifai-python) and downloaded the ZIP
**4.** Unzipped the package and tried to run **setup.py**, first time I got the following error after running the code in IDLE:
```
Traceback (most recent call last):
      File "<pyshell#0>", line 1, in <module>
       from setuptools import setup, find_packages
    ImportError: No module named setuptools
```
**5.** Downloaded **get-pip.py** from [here](https://packaging.python.org/installing/#install-pip-setuptools-and-wheel) and did run it, but then got another error while trying to run **setup.py**:
`error: no commands supplied`

So I'm not sure what I should do next and even after a successful installation of Clarifai API Python Client, should I run the suggested codes like the following, in the Python command line?
  `pip install clarifai==2.0.20`

Thanks in advance.

**Comment by ajbowler** [comment]
That error you're getting is probably unrelated to this project since it happened when installing the Clarifai client. Google recommends trying this:

https://pypi.python.org/pypi/setuptools

I haven't had this issue when installing but I'm also running off of Windows 10. @ThomasKearney did you ever have this issue?

**Comment by Sepehr2016** [comment]
@ajbowler Thanks. Which version of Python 2.7 did you use that has been proven to work?
**EDIT**: Tried many solutions, but there are new errors each time. This is the latest one:

![error](https://cloud.githubusercontent.com/assets/16511601/24287254/94480728-1096-11e7-985d-8e3be26e1619.png)

There are two folders named "setuptools-34.3.2.dist-info" and "setuptools" in `C:\Python27\Lib\site-packages` directory, also "clarifai-2.0.20.dist-info" and "clarifai", but I can't set my Clarifai credientals.

My Python version is 2.7.13.

**Comment by Sepehr2016** [comment]
Alright, I fixed the issue with Clarifai API Python Client, using help from different sources, including [this one](https://github.com/Clarifai/clarifai-python/issues/50). I've tested [this example](https://github.com/Clarifai/clarifai-python#getting-started) from Clarifai and it worked.
But there is a problem with **clarifai-photo-sorter**, here's a report of what happens:
```
PS C:\clarifai-photo-sorter-master> python photo_sorter.py IMG
Begin processing images...

Traceback (most recent call last):
  File "photo_sorter.py", line 35, in <module>
    result = clarifai_api.tag_images(open(orig_photo_dir + image_paths[path], 'rb'))['results'][0]['result']['tag']['cla
sses']
  File "C:\Python27\lib\site-packages\clarifai\client\client.py", line 240, in tag
    language=language)
  File "C:\Python27\lib\site-packages\clarifai\client\client.py", line 606, in _multi_data_op
    media = self._process_files(files)
  File "C:\Python27\lib\site-packages\clarifai\client\client.py", line 527, in _process_files
    self._check_batch_size(input_files)
  File "C:\Python27\lib\site-packages\clarifai\client\client.py", line 551, in _check_batch_size
    self.get_info()  # sets the image size and other such info from server.
  File "C:\Python27\lib\site-packages\clarifai\client\client.py", line 174, in get_info
    self._get_json_headers, self._get_json_response, url, kwargs)
  File "C:\Python27\lib\site-packages\clarifai\client\client.py", line 675, in _get_raw_response
    headers = header_func()
  File "C:\Python27\lib\site-packages\clarifai\client\client.py", line 661, in _get_json_headers
    headers = self._get_authorization_headers()
  File "C:\Python27\lib\site-packages\clarifai\client\client.py", line 654, in _get_authorization_headers
    access_token = self.get_access_token()
  File "C:\Python27\lib\site-packages\clarifai\client\client.py", line 157, in get_access_token
    raise ApiError(e.reason)
clarifai.client.client.ApiError: 'UNAUTHORIZED'
```
What's causing this error?

**Comment by FrankHan** [comment]
@Sepehr2016  I met the same question, you can have a look at my response here:
https://community.clarifai.com/t/clarifai-install-and-quick-start-example-when-using-python/485/2?u=frankhan
or this answer:
www.stackoverflow.com/questions/40191269/python-clarifai-confusion-over-setup

**Comment by Sepehr2016** [comment]
@FrankHan Thanks, but I've fixed that issue. Now, I'm stuck at using the clarifai-photo-sorter.

**Comment by ajbowler** [comment]
I'll take a look sometime this week, maybe the credentials are being funny.

FWIW this project I haven't used since like May of last year so it's entirely possible something weird happened with Clarifai.

**Comment by FrankHan** [comment]
ok. 👍
On 03/28/2017 03:51, Sepp wrote:

@FrankHan Thanks, but I've fixed that issue. Now, I'm stuck at using the clarifai-photo-sorter.

**Comment by ajbowler** [comment]
@Sepehr2016 I'm sending you an email with some information to try, post back in this thread after you've given it a try.
